### ISSUE TITLE
Plugin only supports files with name Jenkinsfile

### ISSUE THREAD

**Issue by anton264** [sgwozdz/jenkinsfile-support#28]
A file not having the exact name of 'Jenkinsfile', for example 'Jenkinsfile.groovy' will not be picked up by the plugin. This should be configurable

**Comment by sgwozdz** [comment]
You're correct it won't be picked up automatically. Not sure if it's possible to make it configurable, but worth to try.

**Comment by britho** [comment]
I disagree.  Nowhere in any Jenkins documentation is there support for `.groovy` file extensions.  I don't see the benefit of adding this, nor enabling this as a practice in any way, shape or form.

**Comment by sgwozdz** [comment]
@britho as long as it's not automatic it's fine. I was thinking about the possibility to configure extensions, filenames from a client perspective if it's possible.

**Comment by anton264** [comment]
@britho I agree that by default it should only be `Jenkinsfile`. Jenkins does however have support for different names and some projects might not follow the standard `Jenkinsfile` for different reasons

**Comment by mnezh** [comment]
> I disagree. Nowhere in any Jenkins documentation is there support for `.groovy` file extensions. I don't see the benefit of adding this, nor enabling this as a practice in any way, shape or form.
> 
> For instance, I could have a Jenkinsfile.groovy in any old Java project and have it be completely unrelated to my CI/CD build. It's all about semantics. `Jenkinsfile` is globally recognized as a configuration file.

You can have several `Jenkinsfile*` in one repository, for the different pipelines (e.g. pre-merge, post-merge, nightly etc.)

**Comment by britho** [comment]
I read my original comment and it sounded harsh. My apologies for that.

> @britho as long as it's not automatic it's fine. I was thinking about the possibility to configure extensions, filenames from a client perspective if it's possible.

Agreed.

> @britho I agree that by default it should only be Jenkinsfile. Jenkins does however have support for different names and some projects might not follow the standard Jenkinsfile for different reasons

Good point, that's something I didn't think about.

> You can have several Jenkinsfile* in one repository, for the different pipelines (e.g. pre-merge, post-merge, nightly etc.)

Another great point and this is something I've seen more and more recently.

**Comment by nathanhruby** [comment]
You can add path and extension based hinting in setting.json.  For instance if you had a directory named `Jenkinsfiles` in your config management repo, you could do

```json
{
  "files.associations" : {
    "**/Jenkinsfiles/**/*": "jenkinsfile"
  }
}
```

**Comment by sgwozdz** [comment]
After some investigation, it seems to be impossible to configure this in the extension. It's just raw JSON which is used as an internal config. 

All we can do here is to specify better when file type should be recognised as jenkinsfile. 
According to the docs:
_VS Code uses three hints to determine the language a file will be associated with. Each "hint" can be enriched independently: 1. the extension of the filename (extensions below) 2. the filename (filenames below) 3. the first line inside the file_

Current settings:
`{
    "extensions": [
        ".jenkins",
        ".jenkinsfile"
    ],
    "filenames": [
        "jenkinsfile"
    ]
}`

^^ it's not case sensitive ;) 
I'm closing the ticket because there is no way to make it configurable by the client, current settings are fine, and @nathanhruby provided a nice solution for special cases.
